### PR TITLE
check maxTouchPoints to identify mobile Safari

### LINKED ISSUE #6: iOS detection issue
Hi Feross,

Thanks for making this utility which makes it so easy to solve the annoying ringer mute problem!  I seem to be affected by one small issue with it:

I'm using an iPhone Xs running iOS 13.7 and `navigator.userAgent` returns `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.1.2 Safari/605.1.15`.  Thus it doesn't seem to work (no errors, but still muted), until I replace
`const isIos = /iPhone|iPad|iPod/.test(navigator.userAgent) && AudioContext != null`
with
`const isIos = AudioContext != null`
then, it works great.

Is the latter not a sufficient check, and/or are there practical consequences for running the full body of `unmuteIosAudio` when it isn't needed?

### PR DESCRIPTION
**Pull request by chrisguttandin**
This pull request is intended to fix #6.

### CODE REVIEW

**Comment by feross** [comment]
Checking `navigator.maxTouchPoints` will also detect Android, right? This doesn't seem like the best approach.

**Comment by chrisguttandin** [comment]
To be honest I did not test that. But it should not be a problem since there is no `webkitAudioContext` on Android. Well a very very old version of Chrome on Android might still have it.

**Comment by feross** [comment]
Good point! But then we can remove the user agent check. We can just check `navigator.maxTouchPoints` and `webkitAudioContext`. I'll fix this in a separate commit.

**Comment by feross** [comment]
Published as 3.2.0

**Pull request closed without merging**
